name: Deploy to AWS EKS
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:  
  build:
    name: Build Image
    runs-on: ubuntu-latest   
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Listar archivos
      run: |
        ls -l
